version: '3'
services:
  v2ray:
    restart: always
    image: v2ray/official
    container_name: v2ray-client
    ports:
      - "1080:1080"
      - "1082:1082"
    volumes:
      - ./client/config.json:/etc/v2ray/config.json
