apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray
data:
  config.json: |-
    {
        "log": {
          "loglevel": "warning",
          "access": "/var/log/v2ray/access.log",
          "error": "/var/log/v2ray/error.log"
        },
        "inbounds": [
          {
            "port": 8082,
            "protocol": "vmess",
            "settings": {
              "clients": [
                {
                  "id": "65b30af2-6694-4a4c-9677-54bf7b2b8d10"
                  ,"alterId": 64
                }
              ]
            },
          "streamSettings": {
              "network": "ws",
              "wsSettings": {
                  "path": "/ws"
              }
            }
          }
        ],
        "outbounds": [
          {
            "protocol": "freedom",
            "settings": {}
          }
        ]
      }
